Battery Life Model for LMO/LTO chemistry (#588)
* move daily cycle tracking from lifetime_nmc_t to lifetime_cycle_t

* add LMO/LTO life model with tests; refactor some daily cycling fxns

* add more tests for LMO/LTO model

* fix isnan on linux

* fix linux error: ‘round’ is not a member of ‘std’

* include cmath

* include cmath

* fix Travis build errors

* add missing #include <algorithm>

* Minor bug fixes and adding comments

* delete incomplete constructors for lifetime_state

* lifetime_state: make sub-state structs only when needed by model choice

* fix constructor issues in battery_stateful

* update units